Triggers update & Job scheduler
ForloopAI/forloop_common_structures pull request #4
Opened 2023-11-02 16:53 UTC by ZaiZu2

Dependencies:
- [https://github.com/ForloopAI/forloop_platform/pull/781](url)

Introduces:
- Updated/cleaned up Trigger dataclass/APIschema/DBmodel

2023-11-09 14:51 UTC, DovaX requested changes

2023-11-09 14:51 UTC, DovaX commented on forloop_common_structures/core/trigger.py
> +    frequency: TriggerFrequencyEnum
forloop_modules.XXXXXXX.TriggerFrequencyEnum

2023-11-09 14:51 UTC, DovaX commented on forloop_common_structures/core/trigger.py
> +class TriggerFrequencyEnum(str, Enum):
move to ForloopModules

2023-11-09 14:51 UTC, DovaX commented on forloop_common_structures/core/database.py
> +class DbDialectEnum(str, Enum):
maybe also move to forloop_modules - if it will be used by "queries"

2023-11-11 13:29 UTC, YoungMasterGandalf approved these changes

2023-11-13 13:32 UTC, DovaX approved these changes

2023-11-13 13:32 UTC, merged