Progress stream changes
ForloopAI/forloop_common_structures pull request #5
Opened 2023-11-09 10:47 UTC by ZaiZu2

Dependencies:
- [https://github.com/ForloopAI/forloop_platform/pull/788](https://github.com/ForloopAI/forloop_platform/pull/788)

Introduces:
- Added size/type to `Result`

2023-11-09 14:57 UTC, DovaX commented
Are you sure, this is the correct branch to be merged? I dont see any code changes that are related to *streaming* Otherwise - I have the same comments as for the PR: https://github.com/ForloopAI/forloop_common_structures/pull/4

2023-11-09 14:58 UTC, DovaX requested changes
.

2023-11-10 09:16 UTC, ZaiZu2 commented
No changes in `forloop_common_structures` were necessary specifically for streaming changes.

Changes for `Result` update were necessary, and this update is a part of the corresponding `forloop_platform` PR.

2023-11-13 13:55 UTC, DovaX approved these changes

2023-11-13 14:14 UTC, merged